/**
 * Mirror transform — turns a `git archive HEAD techsales-api` extract into the
 * standalone TechSalesAPI repo (github.com/Rubaraj/TechSalesAPI).
 *
 * Run by scripts/publish-api-mirror.ps1 against a freshly-extracted staging dir.
 * Because the input is always a clean extract, EVERY edit below must match —
 * a miss means techsales-api changed underneath this script, so it exits
 * non-zero rather than publishing a half-transformed tree.
 *
 *   node publish/api-mirror/transform.mjs <staging-dir>
 */
import { readFileSync, writeFileSync, rmSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const stage = process.argv[2];
if (!stage) {
  console.error('usage: node transform.mjs <staging-dir>');
  process.exit(1);
}

let misses = 0;

/** Exact-string edits within one file. */
function edit(relPath, edits) {
  const p = join(stage, relPath);
  if (!existsSync(p)) {
    console.error(`MISSING FILE: ${relPath}`);
    misses++;
    return;
  }
  let s = readFileSync(p, 'utf8').replace(/\r\n/g, '\n');
  for (const [from, to] of edits) {
    if (!s.includes(from)) {
      console.error(`MISS in ${relPath}: ${JSON.stringify(from.slice(0, 60))}`);
      misses++;
      continue;
    }
    s = s.replace(from, to);
  }
  writeFileSync(p, s);
}

// --- 1. package.json: drop scripts whose targets live outside this package ---
// `check:carriers` runs ../scripts/check-no-real-carriers.mjs (monorepo-only, and
// it also guards the frontend). `transform-data` reads ../techsales-app/src/data.
edit('package.json', [
  ['    "transform-data": "tsx src/scripts/transform-sample-data.ts",\n', ''],
  [',\n    "check:carriers": "node ../scripts/check-no-real-carriers.mjs"', ''],
]);

// --- 2. Drop the script itself (it reads from the frontend package) ----------
rmSync(join(stage, 'src/scripts/transform-sample-data.ts'), { force: true });

// --- 3. Runtime messages must not point at a script this repo doesn't have ---
edit('src/scripts/seed.ts', [
  [
    "'Sample directory missing — run `npm run transform-data` first',",
    "'Sample directory missing — data/sample/ ships with this repo; restore it (git checkout -- data/sample)',",
  ],
]);

edit('src/utils/bootstrap.ts', [
  [
    '`Run \\`npm run transform-data\\` (Phase 2b) to generate it.`;',
    '`data/sample/ ships with this repo — restore it with \\`git checkout -- data/sample\\`.`;',
  ],
]);

edit('src/index.ts', [
  [
    "  //    Phase 1 only WARNS when the sample dir is missing — it's generated by\n  //    Phase 2b's `npm run transform-data`. Phase 2b will switch this to\n",
    '  //    Phase 1 only WARNS when the sample dir is missing (it ships in this\n  //    repo under data/sample/). A later phase will switch this to\n',
  ],
]);

// --- 4. INSTRUCTIONS.md: standalone header, docs/ links, no transform-data ---
edit('INSTRUCTIONS.md', [
  [
    '> Companion API for the `techsales-app/` React frontend. Implements the MongoDB backend described in `../MONGODB_BACKEND_PLAN.md`.',
    '> Express + Mongoose API for a Medicare tele-sales agent console, with live-call AI\n> (Twilio telephony, Deepgram transcription and voice agents, a LangChain tool-calling\n> copilot, compliance/coaching detection, supervisor QA, and cost attribution).\n>\n> The React frontend that consumes this API lives in a separate repository and talks to it\n> over HTTP and WebSockets only. Architectural rationale: [`docs/MONGODB_BACKEND_PLAN.md`](docs/MONGODB_BACKEND_PLAN.md).',
  ],
  [
    'For architectural rationale, see `../MONGODB_BACKEND_PLAN.md`.',
    'For architectural rationale, see [`docs/MONGODB_BACKEND_PLAN.md`](docs/MONGODB_BACKEND_PLAN.md).',
  ],
  [
    'Then seed the Pi from the carrier-sanitized sample data:\n\n```powershell\nnpm run transform-data    # techsales-app/src/data/* → techsales-api/data/sample/* (carriers anonymized)\nnpm run seed -- --reset   # drop both DBs on Pi, re-insert, create indexes\n```',
    'Then seed from the bundled sample data (`data/sample/`, already carrier-anonymized):\n\n```powershell\nnpm run seed -- --reset   # drop both DBs, re-insert, create indexes\n```',
  ],
  [
    '| `npm run transform-data` | Read `../techsales-app/src/data/{runtime,lookup}/*.json`, sanitize (carrier rename + URL placeholder + `existingAetnaMember → existingCarrier1Member`), write to `data/sample/*` |\n',
    '',
  ],
  [
    "`medhub_lookup` is regenerable (re-run `transform-data` + `seed`), so it doesn't usually need to ride along.",
    "`medhub_lookup` is regenerable (re-run `seed` from `data/sample/`), so it doesn't usually need to ride along.",
  ],
  [
    "| `npm run seed` complains about missing sample dir | `data/sample/` doesn't exist | Run `npm run transform-data` first |",
    '| `npm run seed` complains about missing sample dir | `data/sample/` was deleted | It ships with this repo — `git checkout -- data/sample` |',
  ],
  [
    '│   │   ├── transform-sample-data.ts      # JSON in → JSON out, with carrier sanitization\n',
    '',
  ],
  [
    'Forgot to update `techsales-api/src/types/*` AND `techsales-app/src/types/*` together after a field rename',
    'Forgot to update this repo’s `src/types/*` AND the frontend’s `src/types/*` together after a field rename',
  ],
  [
    '- `../MONGODB_BACKEND_PLAN.md` — full architectural plan with rationale and risks\n- `../APPLICATION_GUIDE.md` — frontend application guide\n- `../techsales-app/` — the React frontend that consumes this API\n',
    '- [`docs/MONGODB_BACKEND_PLAN.md`](docs/MONGODB_BACKEND_PLAN.md) — full architectural plan with rationale and risks\n- [`docs/AI_BACKEND_PLAN.md`](docs/AI_BACKEND_PLAN.md) — the LangChain / Qdrant / LLM pipeline\n- [`docs/`](docs/) — VM setup, Databricks migration, vector-store option analysis\n',
  ],
]);

// --- 5. Docs copied from the monorepo root: unambiguous key placeholder ------
edit('docs/AI_BACKEND_PLAN.md', [
  [
    '# Anthropic key — paste into techsales-api/.env\nANTHROPIC_API_KEY=sk-ant-...',
    '# Anthropic key — paste into .env\nANTHROPIC_API_KEY=<your-anthropic-api-key>',
  ],
]);

if (misses > 0) {
  console.error(
    `\n${misses} edit(s) did not match. techsales-api has changed underneath this ` +
      `transform — update publish/api-mirror/transform.mjs before publishing.`,
  );
  process.exit(1);
}
console.log('transform: all edits applied');
