import express, { type Express } from 'express';
import cors from 'cors';
import helmet from 'helmet';
import { env, corsOrigins } from './config/env.js';
import { logger } from './config/logger.js';
import { connectMongo } from './config/mongo.js';
import { initRegistry } from './repositories/registry.js';
import { bootstrapJsonStore } from './utils/bootstrap.js';
import { requestLogger } from './middleware/requestLogger.js';
import { errorHandler, notFoundHandler } from './middleware/errorHandler.js';
import { apiRouter } from './routes/index.js';
import { attachTwilioMediaStreamWs } from './ws/twilioMediaStream.ws.js';

async function main(): Promise<void> {
  // 1. Decide the mode — ONE connection attempt; locked for process lifetime.
  const connectResult = await connectMongo();

  // 2. JSON-mode bootstrap. In Mongo mode we still copy sample files (cheap,
  //    no-op when destination exists) so an operator can flip FORCE_JSON=true
  //    later without a re-bootstrap.
  //
  //    Phase 1 only WARNS when the sample dir is missing — it's generated by
  //    Phase 2b's `npm run transform-data`. Phase 2b will switch this to
  //    `panicIfSampleMissing: connectResult.mode === 'json'` per plan §4.
  await bootstrapJsonStore({ panicIfSampleMissing: false });

  // 3. Wire the repository registry.
  initRegistry(connectResult);

  // 4. Build the Express app.
  const app: Express = express();
  app.disable('x-powered-by');
  app.use(helmet());
  app.use(
    cors({
      origin: corsOrigins.length === 0 ? false : corsOrigins,
      credentials: false,
    }),
  );
  app.use(express.json({ limit: '1mb' }));
  app.use(express.urlencoded({ extended: true }));
  app.use(requestLogger);

  app.use('/api', apiRouter);
  app.use(notFoundHandler);
  app.use(errorHandler);

  // 5. Listen.
  const server = app.listen(env.PORT, () => {
    logger.info(
      {
        port: env.PORT,
        mode: connectResult.mode,
        nodeEnv: env.NODE_ENV,
      },
      `Server listening on http://localhost:${env.PORT} (mode=${connectResult.mode})`,
    );
  });

  // 5a. Phase 2 — attach the Twilio Media Streams WebSocket on the same HTTP
  //     server. Only routes `/ws/twilio-media`. No-op for other upgrades.
  if (env.TWILIO_ENABLED) {
    attachTwilioMediaStreamWs(server);
  }

  // 6. Graceful shutdown.
  const shutdown = (signal: string): void => {
    logger.info({ signal }, 'Shutting down');
    server.close(() => {
      logger.info('HTTP server closed');
      process.exit(0);
    });
    // Force-exit after 5s if connections refuse to drain.
    setTimeout(() => {
      logger.warn('Force exiting after shutdown timeout');
      process.exit(1);
    }, 5000).unref();
  };
  process.on('SIGINT', () => shutdown('SIGINT'));
  process.on('SIGTERM', () => shutdown('SIGTERM'));
}

main().catch((err) => {
  logger.error({ err }, 'Fatal: failed to start server');
  process.exit(1);
});
