/**
 * Backend wire-format mirror of `techsales-app/src/types/call.ts`.
 * Kept narrow to the fields the SSE bridge serializes; the FE owns the
 * superset (UI state, etc.).
 *
 * KEEP IN LOCKSTEP: any change here must be mirrored on the FE.
 *
 * Phase 3a additions: `AiAction` union (subset that the stub agent emits)
 * + `ExtractedEntities` shape + two new `CallStreamEvent` variants.
 * Extension is intentionally narrow — the bridge treats action / entity
 * payloads as opaque pass-through; server-side code only inspects the
 * discriminator.
 */

export type Speaker = 'agent' | 'prospect' | 'unknown';

export interface TranscriptChunk {
  id: string;
  text: string;
  /** epoch ms when the chunk was recognized server-side (Deepgram emit time). */
  timestamp: number;
  isFinal: boolean;
  speaker: Speaker;
  /** Deepgram-emitted confidence 0–1. */
  confidence?: number;
}

/**
 * Phase 3a — actions the stub agent emits. The FE union (`techsales-app/src/types/call.ts`)
 * has more variants reserved for Phase 3b+; only the ones the BE actually
 * emits today are mirrored here. The SSE bridge forwards as opaque pass-through.
 */
export type AiAction =
  | { type: 'fill_field'; field: string; value: string | boolean; confidence: number }
  | { type: 'add_drug'; drugName: string; dosage?: string; frequency?: string }
  | { type: 'add_provider'; providerName: string }
  | { type: 'add_pharmacy'; pharmacyName: string }
  | { type: 'show_info'; topic: string; title: string; content: string; links?: { label: string; url: string }[] }
  | { type: 'show_plans_link'; planType: string; zipCode: string; count?: number; url: string }
  | { type: 'show_drug_coverage'; drugName: string; results: unknown }
  | { type: 'show_recommendation'; plans: unknown[] }
  | {
      type: 'compliance_flag';
      phrase: string;
      rule: string;
      suggestion: string;
      severity?: 'info' | 'warn' | 'critical';
      ruleName?: string;
      /** Gap 5 — transcript chunk that tripped the rule (inline marking). */
      chunkId?: string;
    }
  | { type: 'navigate_suggestion'; url: string; reason: string }
  /** Phase 3b.1 — post-call note generated by `noteSummarizer`. Multiple
   *  add_note actions can fire from a single call's stop(); LeadForm
   *  APPENDS each (line-delimited) to the notes textarea. */
  | {
      type: 'add_note';
      text: string;
      category:
        | 'concern'
        | 'preference'
        | 'financial'
        | 'family'
        | 'health_context'
        | 'switching'
        | 'catalog_miss'
        | 'other';
    };

/** Entities accumulated across the call. The agent's per-call accumulator
 *  is typed as the full ExtractedEntities; events on the wire carry only
 *  the new/changed fields via `Partial<ExtractedEntities>`. */
export interface ExtractedEntities {
  drugs: { name: string; dosage?: string; frequency?: string }[];
  providers: { name: string; specialty?: string }[];
  pharmacies: { name: string }[];
  zipCode: string | null;
  dateOfBirth: string | null;
  firstName: string | null;
  lastName: string | null;
  phone: string | null;
  email: string | null;
  /** Required by the Lead model. Captured by the screening assistant's
   *  intake (the rule-based extractor never sets it). */
  gender: 'Male' | 'Female' | null;
  medicareNumber: string | null;
  medicaidNumber: string | null;
  /** Phase 3b — anchor-phrase booleans the extractor sets when the prospect
   *  confirms specific eligibility. Null = unknown (don't auto-fill). */
  isDualEligible: boolean | null;
  isLISEligible: boolean | null;
  planTypeMentions: string[];
  stateCounty: { state?: string; county?: string } | null;
}

export const emptyExtractedEntities = (): ExtractedEntities => ({
  drugs: [],
  providers: [],
  pharmacies: [],
  zipCode: null,
  dateOfBirth: null,
  firstName: null,
  lastName: null,
  phone: null,
  email: null,
  gender: null,
  medicareNumber: null,
  medicaidNumber: null,
  isDualEligible: null,
  isLISEligible: null,
  planTypeMentions: [],
  stateCounty: null,
});

export type ProspectEmotion = 'positive' | 'neutral' | 'confused' | 'frustrated' | 'upset';

export type CoachingFocus = 'compliance' | 'empathy' | 'clarity' | 'pacing' | 'discovery';

/** SSE event union sent over `GET /api/ai/call/analyze`. */
export type CallStreamEvent =
  | { type: 'open'; callSid: string }
  | { type: 'transcript'; chunk: TranscriptChunk }
  | { type: 'call_status'; status: 'connected' | 'ended' | 'not_hosted' }
  | { type: 'actions'; actions: AiAction[] }
  | { type: 'entities'; entities: Partial<ExtractedEntities> }
  | { type: 'emotion'; emotion: ProspectEmotion; confidence: number; ts: number }
  | {
      type: 'coaching';
      source: 'rule' | 'ai';
      tip: string;
      focus: CoachingFocus;
      ts: number;
    }
  | { type: 'error'; error: string }
  /** AI screening — route the watching agent's browser (lead form during
   *  intake, then the saved lead). */
  | { type: 'navigate'; route: string; reason: string }
  /** Gap 7 — LLM degradation state push (on stream open when degraded +
   *  on every transition while the stream is up). */
  | { type: 'ai_health'; status: 'ok' | 'degraded'; reason?: string; ts: number }
  /** Gap 10 — transcript-so-far replay for clients attaching mid-call
   *  (supervisor live view). Finals only, chronological. `tags` carries
   *  the call's accumulated tags (compliance/coaching/emotion/...) so the
   *  live view renders the same inline chips as the persisted record. */
  | {
      type: 'transcript_backfill';
      chunks: TranscriptChunk[];
      tags: Array<{ kind: string; ts: number; data: Record<string, unknown> }>;
      ts: number;
    };
